# Generated by Django 5.1.2 on 2025-01-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
