// @ts-ignore
import type {Metadata} from 'next'
// @ts-ignore
import {ReactNode} from "react";

// These styles apply to every route in the application
import './global.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="fr-FR">
        <body>{children}</body>
        </html>
    )
}