# Generated by Django 5.1.2 on 2024-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_repayment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repayment_deadline',
            field=models.DateField(),
        ),
    ]
