# Generated by Django 5.1.2 on 2025-01-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_repayment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
