# Generated by Django 5.1.2 on 2025-01-05 16:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('numero_identification', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('adresse', models.CharField(default='263 Avenue General Leclerc', max_length=255)),
                ('profil', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNEL', 'Personnel')], default='ETUDIANT', max_length=25)),
                ('formation', models.CharField(default='AUTRE', max_length=255)),
                ('niveau', models.CharField(choices=[('Licence 1', 'licence 1'), ('Licence 2', 'licence 2'), ('Licence 3', 'licence 3'), ('Master 1', 'master 1'), ('Master 2', 'master 2'), ('AUTRE', 'AUTRE')], default='null', max_length=15)),
                ('parcours', models.CharField(choices=[('CLASSIQUE', 'Classique'), ('ALTERNANCE', 'Alternance')], default='null', max_length=25)),
                ('poste', models.CharField(default='null', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.FileField(upload_to='media/')),
                ('certificat_scolarite', models.FileField(upload_to='media/')),
                ('contrat_bail', models.FileField(upload_to='media/')),
                ('rib', models.FileField(upload_to='media/')),
                ('revenus', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPRUNTEUR', 'Emprunteur'), ('INVESTISSEUR', 'Investisseur')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
