# Generated by Django 5.1.2 on 2025-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('EMPRUNTEUR', 'Emprunteur'), ('INVESTISSEUR', 'Investisseur')], default='AUTRE', max_length=15),
        ),
    ]
