# Generated by Django 5.1.2 on 2025-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('EMPRUNTEUR', 'Emprunteur'), ('INVESTISSEUR', 'Investisseur'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=15),
        ),
    ]
